// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfdhut3RhaxfWEVXcMdXkqmHCWTY2oHw',
    appId: '1:846963757273:web:224235a739146e48286ec8',
    messagingSenderId: '846963757273',
    projectId: 'newsapp-cf200',
    authDomain: 'newsapp-cf200.firebaseapp.com',
    storageBucket: 'newsapp-cf200.appspot.com',
    measurementId: 'G-75LTE42TG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYClQGYe84ZBMpW-k3z6jCQ0kYW30Ho4',
    appId: '1:846963757273:android:d91e1cb1bd2cbea2286ec8',
    messagingSenderId: '846963757273',
    projectId: 'newsapp-cf200',
    storageBucket: 'newsapp-cf200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KMmIYRay5h3wAFnf4TR7dDTDsoOK_Wk',
    appId: '1:846963757273:ios:71e1b33e611bfa24286ec8',
    messagingSenderId: '846963757273',
    projectId: 'newsapp-cf200',
    storageBucket: 'newsapp-cf200.appspot.com',
    iosClientId: '846963757273-28mau992io6gmq7q11f8mvo9iheb818u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KMmIYRay5h3wAFnf4TR7dDTDsoOK_Wk',
    appId: '1:846963757273:ios:71e1b33e611bfa24286ec8',
    messagingSenderId: '846963757273',
    projectId: 'newsapp-cf200',
    storageBucket: 'newsapp-cf200.appspot.com',
    iosClientId: '846963757273-28mau992io6gmq7q11f8mvo9iheb818u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
